#!/bin/sh
#
# makesrcdist - make a source distribution of the Rollo CUPS Driver.
#

if test $# != 1; then
	echo "Usage: ./makesrcdist VERSION"
	echo "       ./makesrcdist snapshot"
	exit 1
fi

version=$1

if test "$version" != snapshot; then
    echo Creating tag for release...
    git tag -m "Tag $version" v$version
    git push origin v$version
fi

echo Creating rollo-cups-driver-$version.tar.gz...
git archive --format tar --prefix=rollo-cups-driver-$version/ HEAD | gzip -v9 >rollo-cups-driver-$version.tar.gz

if test "$version" != snapshot; then
    gpg --detach-sign rollo-cups-driver-$version.tar.gz
fi
