#!/bin/sh
#
# makesrcdist - make a source distribution of the Rollo CUPS Driver.
#

if test $# -lt 1; then
    echo "Usage: ./makesrcdist [--snspshot] VERSION"
    exit 1
fi

if test "$1" == "--snapshot"; then
    snapshot=1
    shift
else
    snapshot=0
fi

version=$1

if test $snapshot = 0; then
    echo Creating tag for release...
    git tag -m "Tag $version" v$version
    git push origin v$version
fi

echo Creating rollo-cups-driver-$version.tar.gz...
git archive --format tar --prefix=rollo-cups-driver-$version/ HEAD | gzip -v9 >rollo-cups-driver-$version.tar.gz

if test $snapshot = 0; then
    gpg --detach-sign rollo-cups-driver-$version.tar.gz
fi
